/* ISC license. */

/* Generated by: ./configure */

#ifndef SKALIBS_CONFIG_H
#define SKALIBS_CONFIG_H

#define SKALIBS_VERSION "2.3.9.0"
#define SKALIBS_DEFAULTPATH "/usr/bin:/bin"
#define SKALIBS_ETC "/etc"
#define SKALIBS_SPROOT ""
#define SKALIBS_HOME ""
#undef SKALIBS_FLAG_REPLACE_LIBC
#undef SKALIBS_FLAG_CLOCKISTAI
#undef SKALIBS_FLAG_USERT
#undef SKALIBS_FLAG_USEMON
#define SKALIBS_FLAG_WANTIPV6
#undef SKALIBS_FLAG_PREFERSELECT
#undef SKALIBS_EGD

#endif
